interface DeployFile {
  path: string;
  content: string;
}

interface DeployRequest {
  files: DeployFile[];
  projectName: string;
  vercelToken?: string;
}

interface VercelFileEntry {
  file: string;
  data: string;
  encoding: "utf-8";
}

interface VercelDeployResponse {
  id: string;
  url: string;
  readyState: string;
  alias?: string[];
  error?: { code: string; message: string };
}

export async function POST(request: Request): Promise<Response> {
  const body = (await request.json()) as DeployRequest;
  const { files, projectName, vercelToken } = body;

  const token = vercelToken || process.env.VERCEL_TOKEN;
  if (!token) {
    return Response.json(
      { error: "Vercel API token is required. Set VERCEL_TOKEN in .env.local or enter it in the UI." },
      { status: 400 }
    );
  }

  if (!files || files.length === 0) {
    return Response.json(
      { error: "No files to deploy." },
      { status: 400 }
    );
  }

  const sanitizedName = projectName
    .toLowerCase()
    .replace(/[^a-z0-9-]/g, "-")
    .replace(/-+/g, "-")
    .replace(/^-|-$/g, "")
    .slice(0, 52) || "sdlc-app";

  const vercelFiles: VercelFileEntry[] = files.map((f) => ({
    file: f.path,
    data: f.content,
    encoding: "utf-8" as const,
  }));

  const hasHtml = files.some(
    (f) => f.path.endsWith(".html") || f.path === "index.html"
  );

  if (!hasHtml) {
    vercelFiles.push({
      file: "index.html",
      data: generateIndexHtml(files),
      encoding: "utf-8",
    });
  }

  try {
    const response = await fetch("https://api.vercel.com/v13/deployments", {
      method: "POST",
      headers: {
        "Content-Type": "application/json",
        Authorization: `Bearer ${token}`,
      },
      body: JSON.stringify({
        name: sanitizedName,
        files: vercelFiles,
        projectSettings: {
          framework: null,
        },
      }),
    });

    const data = (await response.json()) as VercelDeployResponse;

    if (!response.ok) {
      const errorMessage =
        data.error?.message ?? `Vercel API error: ${response.status}`;
      return Response.json({ error: errorMessage }, { status: response.status });
    }

    const deployUrl = `https://${data.url}`;

    return Response.json({
      url: deployUrl,
      deploymentId: data.id,
      readyState: data.readyState,
    });
  } catch (err) {
    const message = err instanceof Error ? err.message : "Unknown error";
    return Response.json({ error: message }, { status: 500 });
  }
}

function generateIndexHtml(files: DeployFile[]): string {
  const fileLinks = files
    .map((f) => {
      const ext = f.path.split(".").pop() ?? "";
      const icon = getFileIcon(ext);
      return `<li><span class="icon">${icon}</span><a href="/${f.path}">${f.path}</a></li>`;
    })
    .join("\n        ");

  return `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Generated Application — SDLCFlow</title>
  <style>
    * { margin: 0; padding: 0; box-sizing: border-box; }
    body { font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif; background: #f8fafc; color: #1e293b; padding: 2rem; }
    .container { max-width: 800px; margin: 0 auto; }
    h1 { font-size: 1.5rem; margin-bottom: 0.5rem; }
    .subtitle { color: #64748b; margin-bottom: 2rem; font-size: 0.875rem; }
    .badge { display: inline-block; background: #e0e7ff; color: #4338ca; padding: 0.25rem 0.75rem; border-radius: 9999px; font-size: 0.75rem; font-weight: 600; margin-bottom: 1.5rem; }
    ul { list-style: none; }
    li { padding: 0.75rem 1rem; border: 1px solid #e2e8f0; border-radius: 0.5rem; margin-bottom: 0.5rem; background: white; display: flex; align-items: center; gap: 0.75rem; }
    li:hover { border-color: #818cf8; }
    a { color: #4338ca; text-decoration: none; font-weight: 500; }
    a:hover { text-decoration: underline; }
    .icon { font-size: 1.25rem; }
  </style>
</head>
<body>
  <div class="container">
    <div class="badge">Generated by SDLCFlow</div>
    <h1>Your Application Files</h1>
    <p class="subtitle">${files.length} files generated via the SDLC process</p>
    <ul>
        ${fileLinks}
    </ul>
  </div>
</body>
</html>`;
}

function getFileIcon(ext: string): string {
  const icons: Record<string, string> = {
    html: "🌐",
    css: "🎨",
    js: "📜",
    ts: "📘",
    tsx: "⚛️",
    jsx: "⚛️",
    json: "📋",
    md: "📝",
    py: "🐍",
    java: "☕",
    go: "🔵",
    rs: "🦀",
    sql: "🗄️",
    yml: "⚙️",
    yaml: "⚙️",
    dockerfile: "🐳",
    sh: "🖥️",
  };
  return icons[ext.toLowerCase()] ?? "📄";
}
